name: "Build & Release"

on:
  workflow_dispatch:
    branches: main

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Clone Repository
        run: git clone https://${{secrets.SECRET_KEY}}@github.com/punisher-303/DoodleMoviesApp.git Doodle  # Clones into shorter path "./Doodle"

      - name: Install Dependencies
        run: |
          cd Doodle
          npm install

      - name: Create keystore file
        run: |
          cd Doodle
          $b64 = "${{ secrets.KEY_STORE }}"
          $filename = "./android/Doodle.jks"
          $bytes = [Convert]::FromBase64String($b64)
          [IO.File]::WriteAllBytes($filename, $bytes)

      - name: Create Keystore properties
        run: |
          cd Doodle
          echo keyPassword=${{ secrets.KEY_PASSWORD }} > ./android/key.properties
          echo storePassword=${{ secrets.STORE_PASSWORD }} >> ./android/key.properties
          echo keyAlias=${{ secrets.KEY_ALIAS }} >> ./android/key.properties

      - name: Build App file
        run: |
          cd Doodle/android
          ./gradlew assembleRelease

      - name: Rename APK files
        run: |
          cd Doodle
          Rename-Item -Path "./android/app/build/outputs/apk/release/Doodle-universal-v9.6.4.apk" -NewName "Doodle Movies-Universal-v9.6.4.apk"
          Rename-Item -Path "./android/app/build/outputs/apk/release/Doodle-armeabi-v7a-v9.6.4.apk" -NewName "Doodle Movies-32bit-v9.6.4.apk"
          Rename-Item -Path "./android/app/build/outputs/apk/release/Doodle-arm64-v8a-v9.6.4.apk" -NewName "Doodle Movies-64bit-v9.6.4.apk"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: |
            Doodle/android/app/build/outputs/apk/release/Doodle Movies-Universal-v9.6.4.apk
            Doodle/android/app/build/outputs/apk/release/Doodle Movies-32bit-v9.6.4.apk
            Doodle/android/app/build/outputs/apk/release/Doodle Movies-64bit-v9.6.4.apk

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            Doodle/android/app/build/outputs/apk/release/Doodle Movies-Universal-v9.6.4.apk
            Doodle/android/app/build/outputs/apk/release/Doodle Movies-32bit-v9.6.4.apk
            Doodle/android/app/build/outputs/apk/release/Doodle Movies-64bit-v9.6.4.apk
          tag: v9.6.4
          token: ${{secrets.SECRET_KEY}}
          prerelease: true
          allowUpdates: true
          omitBody: true